Endpoints for socket
Syncano/syncano-socket-two-factor-auth pull request #1
Opened 2017-12-12 14:52 UTC by andela-eshaibu

### What PR does
Implement endpoints for two-factor auth socket

2017-12-15 09:20 UTC, Andela-callen commented on src/setup_two_factor.js
> +    return new Promise((resolve, reject) => {
you could use `return await new Promise()`

2017-12-15 09:34 UTC, chinazor-allen reviewed
Seems good

2018-01-04 15:32 UTC, adamwardecki requested changes
Looks good! Please see the comments.

2018-01-04 15:32 UTC, adamwardecki commented on socket.yml
> +        description: "Username of user"
User email

2018-01-04 15:32 UTC, adamwardecki commented on socket.yml
> +        description: "Username of user"
User email

2018-01-04 15:32 UTC, adamwardecki commented on src/check-two-factor.js
> +  const {response, users} = Syncano(ctx);
space between vars and braces

2018-01-04 15:32 UTC, adamwardecki commented on src/utils/helpers.js
> +const checkRequired = (val) => {
The helpers are good but i'm wondering if https://github.com/Syncano/syncano-validator-js is not doing the same thing?

2018-01-04 15:32 UTC, adamwardecki commented on src/disable-two-factor.js
> +  const {response, users} = Syncano(ctx);
spaces

2018-01-04 15:32 UTC, adamwardecki commented on src/login.js
> +    if (user.data.two_factor_enabled === false || user.data.two_factor_enabled === null) {
why not `if (!user.data.two_factor_enabled)` ?

2018-01-04 15:32 UTC, adamwardecki commented on src/setup-two-factor.js
> +  const {response, users} = Syncano(ctx);
i see you are mixing space between paren with no spaces. It's good to settle on one way.

2018-01-04 15:32 UTC, adamwardecki commented on src/setup-two-factor.js
> +    const userToUpdate = await users.where('username', username);
you already made a request for the user in line 39

2018-01-04 15:32 UTC, adamwardecki commented on src/verify-token.js
> +  const checkRequired = validateRequired({ username, token, two_factor_token });
just wondering here: maybe you could wrap up the 11-15 lines into the validateRequired function too? It get's repeated along the scripts.

2018-01-04 15:32 UTC, adamwardecki commented on src/verify-token.js
> +    if (user.two_factor_details === null || user.two_factor_details === '') {
`!user.two_factor_details`

2018-01-04 15:32 UTC, adamwardecki commented on src/verify-token.js
> +      const userToUpdate = await users.where('username', username);
you made the request for a user on line 19

2018-01-04 15:32 UTC, adamwardecki commented on test/check-two-factor.test.js
> +
{ INSTANCE_NAME, firstUserEmail: TEST_USER_EMAIL1, etc... } = process.env

2018-01-04 15:32 UTC, adamwardecki commented on test/check-two-factor.test.js
> +  const CHECK_TWO_FACTOR_URL = `https://api.syncano.io/v2/instances/${process.env.INSTANCE_NAME}/` +
You can add `https://api.syncano.io` as a `base_url` var in the utils file or smth. You are using it in a lot of places.

2018-01-04 15:32 UTC, adamwardecki commented on test/check-two-factor.test.js
> +  const CHECK_TWO_FACTOR_URL = `https://api.syncano.io/v2/instances/${process.env.INSTANCE_NAME}/` +
Actually, it would be best if these urls you use across the tests and the user data went into one test data file and you'd import that into the tests.

2018-01-05 15:56 UTC, adamwardecki approved these changes

2018-01-08 08:47 UTC, merged